# Generated by Django 5.1.5 on 2025-02-04 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_document_file'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='embedding',
            table='api_embedding',
        ),
    ]
